---
- alias: GRCh38-af010-vep115.2_basic
  doi: 10.5281/zenodo.0000000
  genome: GRCh38
  af: "0.10"
  tool: vep115.2
  image_tag: vcfstash:vep115.2_basic
  updated_at: 2025-01-01
  md5: placeholder
  annotation_yaml_md5: placeholder
