---
- alias: cache-hg38-gnomad-4.1joint-AF0100-vep-115.2-basic
  type: cache
  version: "0.3.0"
  genome: hg38
  source: gnomad
  release: 4.1joint
  filt: AF0100
  tool: vep
  tool_version: "115.2"
  preset: basic
  doi: 10.5281/zenodo.17843517
  updated_at: 2025-12-06
  md5: 939f976bcb9a6aee4ced74741d6657a4
  annotation_yaml_md5: placeholder
- alias: bp-hg38-gnomad-4.1joint-AF0100
  type: blueprint
  version: "0.3.0"
  genome: hg38
  source: gnomad
  release: 4.1joint
  filt: AF0100
  doi: 10.5281/zenodo.17843517
  updated_at: 2025-12-06
  md5: 939f976bcb9a6aee4ced74741d6657a4
